function Global:Get-CSIToolCatalog {

    return @(
        [pscustomobject]@{ Id='windows.eventlog'; Text='Event Log Triage'; Tab='Windows'; Section='Windows Health'; Function='Invoke-EventLogTriage'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Shows recent critical and error events from System, Application, and Setup logs.' }
        [pscustomobject]@{ Id='windows.services'; Text='Service Health'; Tab='Windows'; Section='Windows Health'; Function='Invoke-ServiceHealth'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Lists automatic services that are unexpectedly stopped.' }
        [pscustomobject]@{ Id='windows.startup'; Text='Startup Impact'; Tab='Windows'; Section='Windows Health'; Function='Invoke-StartupImpact'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Reviews startup commands and failed scheduled tasks.' }
        [pscustomobject]@{ Id='windows.update'; Text='Windows Update Health'; Tab='Windows'; Section='Windows Health'; Function='Invoke-WindowsUpdateHealth'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks update services and common pending reboot markers.' }
        [pscustomobject]@{ Id='windows.defender'; Text='Defender Security Check'; Tab='Windows'; Section='Windows Health'; Function='Invoke-DefenderSecurityCheck'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks Defender, real-time protection, signatures, and firewall profiles.' }
        [pscustomobject]@{ Id='windows.procexp'; Text='Process Explorer'; Tab='Processes'; Section='Processes And Startup'; Function=''; External='ProcessExplorer'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Inspect process trees, handles, DLLs, signatures, and live resource usage.' }
        [pscustomobject]@{ Id='windows.procmon'; Text='Process Monitor'; Tab='Processes'; Section='Processes And Startup'; Function=''; External='ProcessMonitor'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Trace live file, registry, process, thread, and network activity.' }
        [pscustomobject]@{ Id='windows.domain'; Text='Domain Logon Health'; Tab='Directory'; Section='Domain And Policy'; Function='Invoke-DomainLogonHealth'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks domain membership, secure channel, and domain controller discovery.' }
        [pscustomobject]@{ Id='windows.gpo'; Text='GPO Health'; Tab='Directory'; Section='Domain And Policy'; Function='Invoke-GPOHealth'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Runs a computer-scope Group Policy result summary.' }
        [pscustomobject]@{ Id='windows.dismrepair'; Text='DISM/SFC Repair Path'; Tab='Repair'; Section='Repair And Errors'; Function=''; External=''; Action='Start-GUIDismSfcRepairPath'; RequiresAdmin=$true; RunMode='GuiAction'; Description='Runs DISM CheckHealth, ScanHealth, RestoreHealth, and SFC with an exported log.' }
        [pscustomobject]@{ Id='windows.errorlookup'; Text='Windows Error Lookup'; Tab='Repair'; Section='Repair And Errors'; Function=''; External='WindowsErrorLookup'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Look up Windows error codes, HRESULTs, and Win32 error messages.' }

        [pscustomobject]@{ Id='hardware.health'; Text='Hardware Health'; Tab='Hardware'; Section='Hardware Checks'; Function='Invoke-HardwareHealthDiagnostics'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks Device Manager problem devices, storage, battery, memory, and hardware events.' }
        [pscustomobject]@{ Id='hardware.disk'; Text='Disk Health'; Tab='Hardware'; Section='Hardware Checks'; Function='Invoke-DiskHealth'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks volume free space, physical disk health, and recent disk events.' }
        [pscustomobject]@{ Id='hardware.resources'; Text='Resource Hotspots'; Tab='Hardware'; Section='Hardware Checks'; Function='Invoke-ResourceHotspots'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Shows top CPU and memory consumers.' }
        [pscustomobject]@{ Id='hardware.rammap'; Text='RAMMap'; Tab='Processes'; Section='Processes And Startup'; Function=''; External='RAMMap'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Analyze physical memory usage, standby lists, mapped files, and memory pressure.' }
        [pscustomobject]@{ Id='hardware.minidump'; Text='Minidump Collector'; Tab='Hardware'; Section='Crash Analysis'; Function='Invoke-MinidumpCollectorAnalyzer'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Collects and optionally analyzes recent minidumps and crash evidence.' }
        [pscustomobject]@{ Id='hardware.bluescreenview'; Text='BlueScreenView'; Tab='Hardware'; Section='Crash Analysis'; Function=''; External='BlueScreenView'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open BSOD and minidump details for recent crash troubleshooting.' }
        [pscustomobject]@{ Id='hardware.systeminformer'; Text='System Informer'; Tab='Processes'; Section='Processes And Startup'; Function=''; External='SystemInformer'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Advanced process, service, handle, module, and system activity inspection.' }
        [pscustomobject]@{ Id='hardware.crystaldiskinfo'; Text='CrystalDiskInfo'; Tab='Hardware'; Section='Disk Tools'; Function=''; External='CrystalDiskInfo'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Inspect SMART, temperature, health status, and disk firmware details.' }
        [pscustomobject]@{ Id='hardware.hwinfo'; Text='HWiNFO'; Tab='Hardware'; Section='Hardware Checks'; Function=''; External='HWiNFO'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='View detailed hardware inventory, sensors, thermals, and component status.' }

        [pscustomobject]@{ Id='security.msert'; Text='Microsoft Safety Scanner'; Tab='Security'; Section='Malware And Adware Scanners'; Function=''; External='MicrosoftSafetyScanner'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Run Microsoft''s on-demand malware scanner for suspected infection checks.' }
        [pscustomobject]@{ Id='security.adwcleaner'; Text='Malwarebytes AdwCleaner'; Tab='Security'; Section='Malware And Adware Scanners'; Function=''; External='AdwCleaner'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Find and remove adware, browser hijackers, unwanted programs, and toolbars.' }
        [pscustomobject]@{ Id='security.clamwin'; Text='ClamWin Portable'; Tab='Security'; Section='Malware And Adware Scanners'; Function=''; External='ClamWin'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Run a portable antivirus scan against selected files or folders.' }
        [pscustomobject]@{ Id='security.sigcheck'; Text='Sigcheck'; Tab='Security'; Section='Security Inspection'; Function=''; External='Sigcheck'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Check file signatures, hashes, versions, and unsigned executable files.' }
        [pscustomobject]@{ Id='security.autoruns'; Text='Autoruns'; Tab='Security'; Section='Security Inspection'; Function=''; External='Autoruns'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Review startup locations, services, drivers, scheduled tasks, and persistence points.' }

        [pscustomobject]@{ Id='network.connectivity'; Text='Connectivity Triage'; Tab='Network'; Section='Connectivity'; Function='Invoke-ConnectivityTriage'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Runs fast gateway, DNS, route, and target reachability checks.' }
        [pscustomobject]@{ Id='network.adapterroute'; Text='Adapter Route Health'; Tab='Network'; Section='Connectivity'; Function='Invoke-AdapterRouteHealth'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Reviews adapters, IP settings, gateway routes, and DNS configuration.' }
        [pscustomobject]@{ Id='network.packetloss'; Text='Packet Loss Monitor'; Tab='Network'; Section='Connectivity'; Function='Invoke-PacketLossMonitor'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Runs a live packet loss check against a selected target.' }
        [pscustomobject]@{ Id='network.routetrace'; Text='Live Route Trace'; Tab='Network'; Section='Connectivity'; Function='Invoke-LiveRouteTrace'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Shows a live route trace to help find where traffic slows or fails.' }
        [pscustomobject]@{ Id='network.testnetconnection'; Text='Test-NetConnection'; Tab='Network'; Section='Target Testing'; Function='Invoke-TestNetConnectionTool'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Tests host reachability and optional TCP port connectivity.' }
        [pscustomobject]@{ Id='network.dnspath'; Text='DNS Path Test'; Tab='Network'; Section='Target Testing'; Function='Invoke-DNSPathTest'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks DNS resolution path and resolver behavior.' }
        [pscustomobject]@{ Id='network.portmatrix'; Text='Port Reachability Matrix'; Tab='Network'; Section='Target Testing'; Function='Invoke-PortReachabilityMatrix'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Tests a target against a list of common or custom TCP ports.' }
        [pscustomobject]@{ Id='network.tls'; Text='TLS Certificate Check'; Tab='Network'; Section='Target Testing'; Function='Invoke-TLSCertificateCheck'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks a remote TLS certificate and expiration details.' }
        [pscustomobject]@{ Id='network.tcpview'; Text='TCPView'; Tab='Network'; Section='Target Testing'; Function=''; External='TCPView'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='View live TCP/UDP endpoints, remote addresses, connection state, and owning processes.' }
        [pscustomobject]@{ Id='network.psping'; Text='PsPing'; Tab='Network'; Section='Target Testing'; Function=''; External='PsPing'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Measure ICMP/TCP latency and connectivity from Sysinternals.' }
        [pscustomobject]@{ Id='network.winmtr'; Text='WinMTR'; Tab='Network'; Section='Connectivity'; Function=''; External='WinMTR'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Run continuous traceroute and packet loss monitoring to a target.' }
        [pscustomobject]@{ Id='network.winscp'; Text='WinSCP'; Tab='Remote'; Section='Remote And Transfer'; Function=''; External='WinSCP'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open SFTP, SCP, FTP, and WebDAV file transfer client.' }
        [pscustomobject]@{ Id='network.kitty'; Text='KiTTY'; Tab='Remote'; Section='Remote And Transfer'; Function=''; External='KiTTY'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open a portable SSH and Telnet terminal client.' }
        [pscustomobject]@{ Id='network.putty'; Text='PuTTY'; Tab='Remote'; Section='Remote And Transfer'; Function=''; External='PuTTY'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open a portable SSH, Telnet, and serial terminal client.' }
        [pscustomobject]@{ Id='network.whodat'; Text='WhoDat'; Tab='Remote'; Section='Remote And Transfer'; Function=''; External='WhoDat'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Run WHOIS lookups for domain and public IP ownership checks.' }
        [pscustomobject]@{ Id='network.wireshark'; Text='Wireshark'; Tab='Network'; Section='Packet Capture'; Function=''; External='Wireshark'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Open packet capture and protocol analysis for live or saved captures.' }

        [pscustomobject]@{ Id='discovery.network'; Text='Network Discovery'; Tab='Discovery'; Section='Discovery'; Function='Invoke-NetworkDiscovery'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Discovers local network neighbors and common network details.' }
        [pscustomobject]@{ Id='discovery.portservice'; Text='Port and Service Test'; Tab='Discovery'; Section='Discovery'; Function='Invoke-PortAndServiceTest'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Fingerprints common service ports on a target.' }
        [pscustomobject]@{ Id='discovery.fingerprint'; Text='Service Fingerprinter'; Tab='Discovery'; Section='Discovery'; Function='Invoke-ServiceFingerprinter'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Runs deeper service fingerprinting against selected targets.' }
        [pscustomobject]@{ Id='discovery.arp'; Text='ARP Inventory Exporter'; Tab='Discovery'; Section='Discovery'; Function='Invoke-ARPInventoryExporter'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Exports local ARP neighbor inventory for quick review.' }
        [pscustomobject]@{ Id='discovery.subnet'; Text='Subnet Calculator'; Tab='Discovery'; Section='Utilities'; Function='Invoke-SubnetCalculator'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Calculates subnet ranges, masks, and host counts.' }
        [pscustomobject]@{ Id='discovery.wol'; Text='Wake-on-LAN Tool'; Tab='Discovery'; Section='Utilities'; Function='Invoke-WakeOnLANTool'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Sends a Wake-on-LAN magic packet.' }

        [pscustomobject]@{ Id='infrastructure.exposure'; Text='Local Exposure Inspector'; Tab='Infrastructure'; Section='Infrastructure Services'; Function='Invoke-LocalExposureInspector'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Reviews listening ports and local exposure risk.' }
        [pscustomobject]@{ Id='infrastructure.dhcpscope'; Text='DHCP Scope Inspector'; Tab='Infrastructure'; Section='Infrastructure Services'; Function='Invoke-DHCPScopeInspector'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Reviews DHCP scope health and lease information where available.' }
        [pscustomobject]@{ Id='infrastructure.time'; Text='Time Sync Health'; Tab='Infrastructure'; Section='Infrastructure Services'; Function='Invoke-TimeSyncHealth'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks Windows time source and synchronization state.' }
        [pscustomobject]@{ Id='infrastructure.timereset'; Text='Reset Domain Time'; Tab='Infrastructure'; Section='Infrastructure Services'; Function='Invoke-ResetDomainTimeSource'; External=''; Action=''; RequiresAdmin=$true; RunMode='ConsolePause'; Description='Configures Windows Time to use the domain hierarchy, restarts W32Time, resyncs, and verifies the source.' }
        [pscustomobject]@{ Id='infrastructure.dhcplocator'; Text='DHCP Server / Rogue Locator'; Tab='Infrastructure'; Section='Infrastructure Services'; Function='Invoke-DHCPServerLocator'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Finds current DHCP lease evidence and checks for unexpected DHCP responders.' }
        [pscustomobject]@{ Id='infrastructure.dns'; Text='DNS Diagnostics'; Tab='Infrastructure'; Section='DNS'; Function='Invoke-DNSDiagnostics'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Runs DNS diagnostics for configured resolvers and target lookups.' }

        [pscustomobject]@{ Id='wifi.scan'; Text='Wi-Fi Issue Scan'; Tab='Wi-Fi'; Section='Wi-Fi'; Function='Invoke-WiFiIssueScan'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Runs a quick scan for common Wi-Fi problems.' }
        [pscustomobject]@{ Id='wifi.status'; Text='Wi-Fi Status'; Tab='Wi-Fi'; Section='Wi-Fi'; Function='Invoke-WiFiStatus'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Shows wireless interface state and connection details.' }
        [pscustomobject]@{ Id='wifi.networks'; Text='Wi-Fi Networks'; Tab='Wi-Fi'; Section='Wi-Fi'; Function='Invoke-WiFiNetworks'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Lists visible wireless networks.' }
        [pscustomobject]@{ Id='wifi.profiles'; Text='Wi-Fi Profiles'; Tab='Wi-Fi'; Section='Wi-Fi'; Function='Invoke-WiFiProfiles'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Lists saved Wi-Fi profiles.' }

        [pscustomobject]@{ Id='print.maintenance'; Text='Print Queue Maintenance'; Tab='Print'; Section='Printing'; Function=''; External=''; Action='Start-GUIPrintQueueMaintenance'; RequiresAdmin=$false; RunMode='GuiAction'; Description='Launches your print queue maintenance GUI for print server queue review and spooler actions.' }
        [pscustomobject]@{ Id='print.triage'; Text='Print Spooler Triage'; Tab='Print'; Section='Printing'; Function='Invoke-PrintSpoolerTriage'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Checks local print spooler health, printers, queues, jobs, and common print issues.' }
        [pscustomobject]@{ Id='print.stale'; Text='Stale Printer Cleanup'; Tab='Print'; Section='Printing'; Function='Invoke-StaleLocalPrinterCleanup'; External=''; Action=''; RequiresAdmin=$true; RunMode='ConsolePause'; Description='Finds stale local printer artifacts, old user printer entries, and orphaned printer registry remnants.' }

        [pscustomobject]@{ Id='files.everything'; Text='Everything'; Tab='Files'; Section='Search And Space'; Function=''; External='Everything'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Launch Everything for instant local filename search.' }
        [pscustomobject]@{ Id='files.wiztree'; Text='WizTree'; Tab='Files'; Section='Search And Space'; Function=''; External='WizTree'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Launch WizTree for fast disk space analysis.' }
        [pscustomobject]@{ Id='files.windirstat'; Text='WinDirStat'; Tab='Files'; Section='Search And Space'; Function=''; External='WinDirStat'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Launch WinDirStat to visualize disk usage and large folders.' }
        [pscustomobject]@{ Id='files.winmerge'; Text='WinMerge'; Tab='Files'; Section='Compare And Manage'; Function=''; External='WinMerge'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Compare and merge files or folders.' }
        [pscustomobject]@{ Id='files.kudu'; Text='Kudu'; Tab='Files'; Section='Compare And Manage'; Function=''; External='Kudu'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open a portable file manager for browsing and working with local files.' }
        [pscustomobject]@{ Id='files.handle'; Text='Handle'; Tab='Files'; Section='Compare And Manage'; Function=''; External='Handle'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Find which process has a file, folder, registry key, or object open.' }
        [pscustomobject]@{ Id='files.psexec'; Text='PsExec'; Tab='Files'; Section='Compare And Manage'; Function=''; External='PsExec'; Action=''; RequiresAdmin=$true; RunMode='External'; Description='Run commands locally or remotely when troubleshooting admin access and remote execution.' }
        [pscustomobject]@{ Id='software.notepadpp'; Text='Notepad++'; Tab='Software'; Section='Editors'; Function=''; External='NotepadPlusPlus'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open Notepad++ for logs, scripts, configs, and quick text edits.' }
        [pscustomobject]@{ Id='software.firefoxportable'; Text='Firefox Portable'; Tab='Software'; Section='Portable Browser'; Function=''; External=''; Action='Start-GUIFirefoxPortable'; RequiresAdmin=$false; RunMode='GuiAction'; Description='Launch Firefox Portable from the toolkit with its profile, history, bookmarks, and extensions stored on this drive.' }
        [pscustomobject]@{ Id='software.drawio'; Text='Draw.io'; Tab='Software'; Section='Diagramming'; Function=''; External='Drawio'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open Draw.io for network diagrams, flowcharts, and troubleshooting visuals.' }
        [pscustomobject]@{ Id='software.kompozer'; Text='KompoZer'; Tab='Software'; Section='HTML And Reports'; Function=''; External='KompoZer'; Action=''; RequiresAdmin=$false; RunMode='External'; Description='Open KompoZer for quick HTML or report edits.' }

        [pscustomobject]@{ Id='reports.network'; Text='Network Report Exporter'; Tab='Reports'; Section='Outputs'; Function='Invoke-NetworkReportExporter'; External=''; Action=''; RequiresAdmin=$false; RunMode='ConsolePause'; Description='Exports network report data.' }
    )

}
